apiVersion: 1

datasources:
  - name: devpulse
    type: postgres
    access: proxy
    uid: devpulse-pg
    url: ${DEVPULSE_DB_HOST}:${DEVPULSE_DB_PORT}
    user: ${DEVPULSE_DB_USER}
    database: ${DEVPULSE_DB_NAME}
    isDefault: true
    jsonData:
      sslmode: ${DEVPULSE_DB_SSLMODE}
      postgresVersion: 1500
      timescaledb: false
      database: ${DEVPULSE_DB_NAME}
    secureJsonData:
      password: ${DEVPULSE_DB_PASSWORD}
    editable: true

