package persistence

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/mileschou/devpulse/internal/repo"
)

// RepoPersister persists Repo aggregates.
type RepoPersister struct{ *Persister }

func NewRepoPersister(p *Persister) *RepoPersister { return &RepoPersister{Persister: p} }

// ErrRepoNotFound signals a missing repo lookup.
var ErrRepoNotFound = errors.New("persistence: repo not found")

// defaultPRSyncStart is the floor used when EnsureID creates a fresh
// repo row. Tracked as a named constant so the application default and
// the DB default (NOT NULL DEFAULT 1) cannot drift apart silently.
const defaultPRSyncStart = 1

const repoSelectColumns = `id, provider, owner, repo_name, description,
	default_branch, disabled, pr_sync_start_number`

// FindByID returns the Repo with the given ID, or ErrRepoNotFound.
func (r *RepoPersister) FindByID(ctx context.Context, id string) (repo.Repo, error) {
	q := `SELECT ` + repoSelectColumns + ` FROM repos WHERE id = ?`
	return r.scanOne(ctx, q, id)
}

// FindByFullName returns the Repo whose stored provider=provider and (owner, repo_name)=fullName.
func (r *RepoPersister) FindByFullName(ctx context.Context, provider string, fullName repo.FullName) (repo.Repo, error) {
	q := `SELECT ` + repoSelectColumns + ` FROM repos WHERE provider = ? AND owner = ? AND repo_name = ?`
	return r.scanOne(ctx, q, provider, fullName.Owner, fullName.Name)
}

// ListAll returns every stored repo, ordered by (owner, repo_name) so the
// output of bulk operations like `devpulse sync` is stable across runs.
// Returns an empty slice (not nil) when the store is empty.
func (r *RepoPersister) ListAll(ctx context.Context) ([]repo.Repo, error) {
	q := `SELECT ` + repoSelectColumns + `
	        FROM repos
	       ORDER BY owner, repo_name`

	rows, err := r.QueryCtx(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("repo list: %w", err)
	}
	defer rows.Close()

	out := make([]repo.Repo, 0)
	for rows.Next() {
		got, err := scanRepoRow(rows)
		if err != nil {
			return nil, fmt.Errorf("repo list scan: %w", err)
		}
		out = append(out, got)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repo list rows: %w", err)
	}
	return out, nil
}

// scanOne runs a single-row SELECT and decodes it into Repo. It returns
// ErrRepoNotFound on sql.ErrNoRows.
func (r *RepoPersister) scanOne(ctx context.Context, q string, args ...any) (repo.Repo, error) {
	got, err := scanRepoRow(r.QueryRowCtx(ctx, q, args...))
	if errors.Is(err, sql.ErrNoRows) {
		return repo.Repo{}, ErrRepoNotFound
	}
	if err != nil {
		return repo.Repo{}, fmt.Errorf("repo find: %w", err)
	}
	return got, nil
}

// scanRepoRow accepts either *sql.Row or *sql.Rows so a single decoding
// path serves both single-row and iterator callers. Kept private to the
// persistence package.
func scanRepoRow(s rowScanner) (repo.Repo, error) {
	var (
		got                       repo.Repo
		provider, owner, repoName string
		description               sql.NullString
		defaultBranch             string
		disabled                  bool
		prSyncStartNumber         int
	)
	if err := s.Scan(
		&got.ID, &provider, &owner, &repoName,
		&description, &defaultBranch, &disabled, &prSyncStartNumber,
	); err != nil {
		return repo.Repo{}, err
	}

	got.Name = repo.FullName{Owner: owner, Name: repoName}
	got.Provider = provider
	if description.Valid {
		s := description.String
		got.Description = &s
	}
	got.DefaultBranch = defaultBranch
	got.Disabled = disabled
	got.PRSyncStartNumber = prSyncStartNumber
	return got, nil
}

// Create inserts a new Repo row. The ID is generated by the persister.
// Metadata fields on r (Description, DefaultBranch, Disabled,
// PRSyncStartNumber) are persisted as-is; pass a zero-value Repo for a
// minimal row — Create promotes PRSyncStartNumber == 0 to the default
// floor (1) so callers never have to remember the constant.
func (r *RepoPersister) Create(ctx context.Context, provider string, fullName repo.FullName, url string, meta repo.Repo) (repo.Repo, error) {
	id := r.NewID()
	now := r.Now()

	start := meta.PRSyncStartNumber
	if start < 1 {
		start = defaultPRSyncStart
	}

	const q = `INSERT INTO repos
	           (id, provider, owner, repo_name, url, description, default_branch,
	            disabled, pr_sync_start_number, created_at, updated_at)
	           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`

	if _, err := r.ExecCtx(ctx, q,
		id,
		provider,
		fullName.Owner,
		fullName.Name,
		url,
		nullableString(meta.Description),
		meta.DefaultBranch,
		meta.Disabled,
		start,
		now,
		now,
	); err != nil {
		return repo.Repo{}, fmt.Errorf("repo create: %w", err)
	}

	created := repo.Repo{
		ID:                id,
		Name:              fullName,
		Description:       meta.Description,
		DefaultBranch:     meta.DefaultBranch,
		Disabled:          meta.Disabled,
		PRSyncStartNumber: start,
	}
	return created, nil
}

// EnsureID returns the existing Repo for (provider, fullName), or creates
// a fresh minimal row (no metadata) and returns it. The url defaults to
// https://github.com/<owner>/<name> when provider == "github".
//
// Use UpdateMetadata after a successful GitHub fetch to populate the
// description / default_branch / disabled columns.
func (r *RepoPersister) EnsureID(ctx context.Context, provider string, fullName repo.FullName) (repo.Repo, error) {
	got, err := r.FindByFullName(ctx, provider, fullName)
	if err == nil {
		return got, nil
	}
	if !errors.Is(err, ErrRepoNotFound) {
		return repo.Repo{}, err
	}
	return r.Create(ctx, provider, fullName, defaultURL(provider, fullName), repo.Repo{})
}

// UpdatePRSyncStart sets the PR-sync floor for an existing repo. The
// caller is expected to have validated `n >= 1`; this method enforces
// it as defense-in-depth in case the validation is bypassed (CLI flag,
// programmatic caller, etc.). The DB has the same constraint at the
// CHECK level on dialects that support it (PostgreSQL, MySQL 8.0.16+).
//
// Returns ErrRepoNotFound when no row matches `id`.
func (r *RepoPersister) UpdatePRSyncStart(ctx context.Context, id string, n int) error {
	if n < 1 {
		return fmt.Errorf("pr sync start: must be >= 1, got %d", n)
	}

	const q = `UPDATE repos SET pr_sync_start_number = ?, updated_at = ? WHERE id = ?`
	res, err := r.ExecCtx(ctx, q, n, r.Now(), id)
	if err != nil {
		return fmt.Errorf("repo update pr sync start: %w", err)
	}
	rows, err := res.RowsAffected()
	if err != nil {
		// All three drivers in use (pgx, go-sql-driver/mysql,
		// mattn/go-sqlite3) implement RowsAffected for UPDATE, so this
		// branch should be unreachable in practice. If it happens we
		// log + return success rather than fail loud: the UPDATE itself
		// did not error, and there is no way to distinguish "no row
		// matched" from "driver failed to report" without this signal.
		r.Logger.Warn("repo update pr sync start: RowsAffected unavailable",
			"id", id, "err", err.Error())
		return nil
	}
	if rows == 0 {
		return ErrRepoNotFound
	}
	return nil
}

// UpdateMetadata writes the description / default_branch / disabled
// columns for an existing repo and bumps updated_at.
//
// PRSyncStartNumber is intentionally *not* written here: it is operator
// configuration, not GitHub-sourced metadata. Use UpdatePRSyncStart to
// change it.
func (r *RepoPersister) UpdateMetadata(ctx context.Context, id string, meta repo.Repo) error {
	const q = `UPDATE repos
	           SET description = ?, default_branch = ?, disabled = ?, updated_at = ?
	           WHERE id = ?`
	if _, err := r.ExecCtx(ctx, q,
		nullableString(meta.Description),
		meta.DefaultBranch,
		meta.Disabled,
		r.Now(),
		id,
	); err != nil {
		return fmt.Errorf("repo update metadata: %w", err)
	}
	return nil
}

func defaultURL(provider string, fn repo.FullName) string {
	if provider == "github" {
		return "https://github.com/" + fn.String()
	}
	return ""
}

func nullableString(p *string) any {
	if p == nil {
		return nil
	}
	return *p
}
