package persistence

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/mileschou/devpulse/internal/repo"
)

// RepoPersister persists Repo aggregates.
type RepoPersister struct{ *Persister }

func NewRepoPersister(p *Persister) *RepoPersister { return &RepoPersister{Persister: p} }

// ErrRepoNotFound signals a missing repo lookup.
var ErrRepoNotFound = errors.New("persistence: repo not found")

// FindByID returns the Repo with the given ID, or ErrRepoNotFound.
func (r *RepoPersister) FindByID(ctx context.Context, id string) (repo.Repo, error) {
	const q = `SELECT id, provider, owner, repo_name, description, default_branch, disabled
	           FROM repos WHERE id = ?`
	return r.scanOne(ctx, q, id)
}

// FindByFullName returns the Repo whose stored provider=provider and (owner, repo_name)=fullName.
func (r *RepoPersister) FindByFullName(ctx context.Context, provider string, fullName repo.FullName) (repo.Repo, error) {
	const q = `SELECT id, provider, owner, repo_name, description, default_branch, disabled
	           FROM repos WHERE provider = ? AND owner = ? AND repo_name = ?`
	return r.scanOne(ctx, q, provider, fullName.Owner, fullName.Name)
}

// scanOne runs a single-row SELECT and decodes it into Repo. It returns
// ErrRepoNotFound on sql.ErrNoRows.
func (r *RepoPersister) scanOne(ctx context.Context, q string, args ...any) (repo.Repo, error) {
	var (
		got                       repo.Repo
		provider, owner, repoName string
		description               sql.NullString
		defaultBranch             string
		disabled                  bool
	)
	err := r.QueryRowCtx(ctx, q, args...).Scan(
		&got.ID, &provider, &owner, &repoName,
		&description, &defaultBranch, &disabled,
	)
	if errors.Is(err, sql.ErrNoRows) {
		return repo.Repo{}, ErrRepoNotFound
	}
	if err != nil {
		return repo.Repo{}, fmt.Errorf("repo find: %w", err)
	}

	got.Name = repo.FullName{Owner: owner, Name: repoName}
	if description.Valid {
		s := description.String
		got.Description = &s
	}
	got.DefaultBranch = defaultBranch
	got.Disabled = disabled
	return got, nil
}

// Create inserts a new Repo row. The ID is generated by the persister.
// Metadata fields on r (Description, DefaultBranch, Disabled) are
// persisted as-is; pass a zero-value Repo for a minimal row.
func (r *RepoPersister) Create(ctx context.Context, provider string, fullName repo.FullName, url string, meta repo.Repo) (repo.Repo, error) {
	id := r.NewID()
	now := r.Now()

	const q = `INSERT INTO repos
	           (id, provider, owner, repo_name, url, description, default_branch, disabled, created_at, updated_at)
	           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`

	if _, err := r.ExecCtx(ctx, q,
		id,
		provider,
		fullName.Owner,
		fullName.Name,
		url,
		nullableString(meta.Description),
		meta.DefaultBranch,
		meta.Disabled,
		now,
		now,
	); err != nil {
		return repo.Repo{}, fmt.Errorf("repo create: %w", err)
	}

	created := repo.Repo{
		ID:            id,
		Name:          fullName,
		Description:   meta.Description,
		DefaultBranch: meta.DefaultBranch,
		Disabled:      meta.Disabled,
	}
	return created, nil
}

// EnsureID returns the existing Repo for (provider, fullName), or creates
// a fresh minimal row (no metadata) and returns it. The url defaults to
// https://github.com/<owner>/<name> when provider == "github".
//
// Use UpdateMetadata after a successful GitHub fetch to populate the
// description / default_branch / disabled columns.
func (r *RepoPersister) EnsureID(ctx context.Context, provider string, fullName repo.FullName) (repo.Repo, error) {
	got, err := r.FindByFullName(ctx, provider, fullName)
	if err == nil {
		return got, nil
	}
	if !errors.Is(err, ErrRepoNotFound) {
		return repo.Repo{}, err
	}
	return r.Create(ctx, provider, fullName, defaultURL(provider, fullName), repo.Repo{})
}

// UpdateMetadata writes the description / default_branch / disabled
// columns for an existing repo and bumps updated_at.
func (r *RepoPersister) UpdateMetadata(ctx context.Context, id string, meta repo.Repo) error {
	const q = `UPDATE repos
	           SET description = ?, default_branch = ?, disabled = ?, updated_at = ?
	           WHERE id = ?`
	if _, err := r.ExecCtx(ctx, q,
		nullableString(meta.Description),
		meta.DefaultBranch,
		meta.Disabled,
		r.Now(),
		id,
	); err != nil {
		return fmt.Errorf("repo update metadata: %w", err)
	}
	return nil
}

func defaultURL(provider string, fn repo.FullName) string {
	if provider == "github" {
		return "https://github.com/" + fn.String()
	}
	return ""
}

func nullableString(p *string) any {
	if p == nil {
		return nil
	}
	return *p
}

// touch updates updated_at — used by enrichment writes elsewhere.
func (r *RepoPersister) touch(ctx context.Context, id string, t time.Time) error {
	const q = `UPDATE repos SET updated_at = ? WHERE id = ?`
	_, err := r.ExecCtx(ctx, q, t, id)
	return err
}
