package persistence

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/mileschou/devpulse/internal/repo"
)

// RepoPersister persists Repo aggregates.
type RepoPersister struct{ *Persister }

func NewRepoPersister(p *Persister) *RepoPersister { return &RepoPersister{Persister: p} }

// ErrRepoNotFound signals a missing repo lookup.
var ErrRepoNotFound = errors.New("persistence: repo not found")

// FindByID returns the Repo with the given ID, or ErrRepoNotFound.
func (r *RepoPersister) FindByID(ctx context.Context, id string) (repo.Repo, error) {
	const q = `SELECT id, type, name FROM repos WHERE id = ?`
	var got repo.Repo
	var typ, name string
	err := r.QueryRowCtx(ctx, q, id).Scan(&got.ID, &typ, &name)
	if errors.Is(err, sql.ErrNoRows) {
		return repo.Repo{}, ErrRepoNotFound
	}
	if err != nil {
		return repo.Repo{}, fmt.Errorf("repo find: %w", err)
	}

	full, err := repo.ParseFullName(name)
	if err != nil {
		return repo.Repo{}, fmt.Errorf("repo find: invalid stored name %q: %w", name, err)
	}
	got.Name = full
	return got, nil
}

// FindByFullName returns the Repo whose stored type='github' and name=fullName.
func (r *RepoPersister) FindByFullName(ctx context.Context, platform string, fullName repo.FullName) (repo.Repo, error) {
	const q = `SELECT id, type, name FROM repos WHERE type = ? AND name = ?`
	var got repo.Repo
	var typ, name string
	err := r.QueryRowCtx(ctx, q, platform, fullName.String()).Scan(&got.ID, &typ, &name)
	if errors.Is(err, sql.ErrNoRows) {
		return repo.Repo{}, ErrRepoNotFound
	}
	if err != nil {
		return repo.Repo{}, fmt.Errorf("repo find by name: %w", err)
	}

	full, err := repo.ParseFullName(name)
	if err != nil {
		return repo.Repo{}, fmt.Errorf("repo find by name: invalid stored name %q: %w", name, err)
	}
	got.Name = full
	return got, nil
}

// Create inserts a new Repo row. The ID is generated by the persister.
func (r *RepoPersister) Create(ctx context.Context, platform string, fullName repo.FullName, url string) (repo.Repo, error) {
	id := r.NewID()
	now := r.Now()

	const q = `INSERT INTO repos (id, slug, name, type, url, human_signals, created_at, updated_at)
	           VALUES (?, ?, ?, ?, ?, ?, ?, ?)`

	if _, err := r.ExecCtx(ctx, q,
		id,
		fullName.String(), // slug — same as name for now; reserve a separate column for user-facing alias later
		fullName.String(),
		platform,
		url,
		"[]",
		now,
		now,
	); err != nil {
		return repo.Repo{}, fmt.Errorf("repo create: %w", err)
	}

	return repo.Repo{ID: id, Name: fullName}, nil
}

// EnsureID returns the existing Repo's ID for (platform, fullName), or
// creates a fresh row and returns the new ID. The url defaults to
// https://github.com/<owner>/<name> when platform == "github".
func (r *RepoPersister) EnsureID(ctx context.Context, platform string, fullName repo.FullName) (repo.Repo, error) {
	got, err := r.FindByFullName(ctx, platform, fullName)
	if err == nil {
		return got, nil
	}
	if !errors.Is(err, ErrRepoNotFound) {
		return repo.Repo{}, err
	}
	return r.Create(ctx, platform, fullName, defaultURL(platform, fullName))
}

func defaultURL(platform string, fn repo.FullName) string {
	if platform == "github" {
		return "https://github.com/" + fn.String()
	}
	return ""
}

// touch updates updated_at — used by enrichment writes elsewhere.
func (r *RepoPersister) touch(ctx context.Context, id string, t time.Time) error {
	const q = `UPDATE repos SET updated_at = ? WHERE id = ?`
	_, err := r.ExecCtx(ctx, q, t, id)
	return err
}

